# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'places' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for places
  
  # Required by RNFirebase
pod 'Firebase/Core', '~> 5.15.0'
pod 'Firebase/Storage', '~> 5.15.0'
pod 'Firebase/Auth', '~> 5.15.0'
pod 'Firebase/Database', '~> 5.15.0'

  target 'places-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'placesTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'places-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!


end
